# Generated by Django 3.1 on 2020-08-10 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('remk', models.CharField(blank=True, max_length=500, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=200)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=200)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='UnionCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=200)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.district')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.division')),
            ],
            options={
                'db_table': 'union_council',
            },
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=200)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.district')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.division')),
                ('added_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upazila',
            },
        ),
        migrations.CreateModel(
            name='VoteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=200)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote_info',
            },
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=50)),
                ('last_Name', models.CharField(max_length=50, null=True)),
                ('nid', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=30)),
                ('contact_No', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('marital_Status', models.CharField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried'), ('Divorced', 'Divorced')], max_length=20)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=20)),
                ('voter_area', models.CharField(max_length=100)),
                ('remk', models.CharField(blank=True, max_length=500, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.district')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.division')),
                ('UnionCouncil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.unioncouncil')),
                ('Upazila', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.upazila')),
                ('added_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voter',
            },
        ),
        migrations.CreateModel(
            name='VoteWiseVoterList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.BigIntegerField()),
                ('tokenNumber', models.IntegerField(unique=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('VoteInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.voteinfo')),
                ('Voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.voter')),
                ('added_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote_wise_voter',
            },
        ),
        migrations.CreateModel(
            name='VoteCalculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.candidate')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VoterUser', to=settings.AUTH_USER_MODEL)),
                ('VoteInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.voteinfo')),
                ('added_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote_calculation',
            },
        ),
        migrations.AddField(
            model_name='unioncouncil',
            name='Upazila',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.upazila'),
        ),
        migrations.AddField(
            model_name='unioncouncil',
            name='added_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('caption', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='static/images/')),
                ('desc', models.TextField()),
                ('remk', models.CharField(blank=True, max_length=500, null=True)),
                ('is_Active', models.BooleanField(default=True)),
                ('date_Created', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_Updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'party',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='Division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.division'),
        ),
        migrations.AddField(
            model_name='district',
            name='added_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.party'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CandidateUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='VoteInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.voteinfo'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='Voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteApp_BackEnd.voter'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='added_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
